name: sync-frappe-master-branch
on:
  schedule:
    # Run the job daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # This allows to run the actions manually 

jobs:
  sync-frappe-master-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Pull from frappe master branch and Push to iVendNext master branch
        env:
          SUPER_SECRET: ${{ secrets.MNJ_GITHUB_TOKEN }}
        run: | 
          git config --global user.email "mahendra.jha@citixsys.com"
          git config --global user.name "cxs-mahendra"
          git clone "https://$SUPER_SECRET@github.com/ivendnext/Agent.git"
          cd Agent
          git remote add public https://github.com/frappe/agent.git
          git pull public master --rebase
          git push origin master -f

          

          
          
          
          
          
          
    
