
name: Sync-Master-Branch
on:
  schedule:
    # Run the job daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Sync-Master-Branch:
    runs-on: ubuntu-latest

    steps:
      - name: Pull From Frappe Public Repo and Push to Private Repo
        env:
          SUPER_SECRET: ${{ secrets.MNJ_GITHUB_TOKEN }}
        run: | 
          git config --global user.email "mahendra.jha@citixsys.com"
          git config --global user.name "cxs-mahendra"
          git clone "https://$SUPER_SECRET@github.com/ivendnext/Agent.git"
          cd Agent
          git remote add public https://github.com/frappe/agent.git
          git pull public master --rebase
          git push origin master -f

          

          
          
          
          
          
          
    
